# 支持的种类 -> 4个
#  checkerboard
#  charuco
#  aruco
#  april
#  circlegrid


# checkerboard 需要向内收缩 -> 数格子-1
type: checkerboard
height: 8
width: 11

# charucoboard 不需要向内收缩 -> 数格子
# type: charucoboard
# height: 6
# width: 5
# suqare_length: 0.03
# marker_length: 0.022

# TODO