# 支持的种类 -> 4个
#  checkerboard
#  charuco
#  aruco
#  april
#  circlegrid

type: checkerboard
height: 8
width: 11

# type: charucoboard
# height: 6
# width: 5
# suqare_length: 0.03
# marker_length: 0.022

# TODO