# 文件结构
# image_path
#  - board
#     - [intrinsic.json] # 可选:提供的内参初始值
#     - cam*
#  - empty
#     - cam*
#  - pole
#     - [extrinsic.json] # 可选:提供的外参初始值
#     - cam*

cam_num: 7

board: !include "config/board/checkerboard_11_8.yaml"
pole: !include "config/pole/pole760.yaml"

image_path: "imageCollect/imageCollectOutdoorArchery"

maskBlobParam:
  minThreshold: 220
  minAreaRatio: 1.0e-7
  maxAreaRatio: 1.0e-2
  expandSize: 3

poleBlobParam:
  minThreshold: 240
  minAreaRatio: 2.0e-6
  maxAreaRatio: 6.5e-4
  minCircularity: 0.2
  minConvexity: 0.2
  minInertiaRatio: 0.1
  lineAngle: 2

wandBlobParam:
  minThreshold: 240
  minAreaRatio: 2.0e-6
  maxAreaRatio: 6.5e-4
  minCircularity: 0.2
  minConvexity: 0.2
  minInertiaRatio: 0.1

# worldCoordParam: !include "config/point/point_archery.yaml"
worldCoordParam: !include "config/wand/wand_archery.yaml"





