# 文件结构
# image_path
#  - board
#     - [intrinsic.json] # 可选:提供的内参初始值
#     - cam*
#  - empty
#     - cam*
#  - pole
#     - [extrinsic.json] # 可选:提供的外参初始值
#     - cam*

cam_num: 6

board: !include "/home/wenzihao/Desktop/wandCalibration/config/board/board_sample.yaml"
pole: !include "/home/wenzihao/Desktop/wandCalibration/config/pole/pole760.yaml"

image_path: "/home/wenzihao/Desktop/wandCalibration/imageCollect"

maskBlobParam:
  minThreshold: 220
  minAreaRatio: 1.0e-7
  maxAreaRatio: 1.0e-2
  expandSize: 3

poleBlobParam:
  minThreshold: 240
  minAreaRatio: 5.0e-6
  maxAreaRatio: 6.5e-4
  minCircularity: 0.2
  minConvexity: 0.2
  minInertiaRatio: 0.1
  lineAngle: 2







